spring:
  data:
    redis:
      host: redis
      port: 6379

services:
  user-service:
    url: http://user-service:8081
  catalog-service:
    url: http://catalog-service:8082
  booking-service:
    url: http://booking-service:8083
  payment-service:
    url: http://payment-service:8084

logging:
  level:
    root: INFO
    com.bookmyshow.gateway: INFO
    org.springframework.cloud.gateway: INFO
